---
- name: Création automatique d’une VM RHEL sur Proxmox
  hosts: localhost
  gather_facts: no
  vars:
    proxmox_host: "192.168.1.56"
    proxmox_user: "root@pam"
    proxmox_password: "baraka"
    node_name: "pve"
    vm_id: 200
    vm_name: "rhel-auto"
    iso_name: "rhel-9.iso"        # vérifie le nom exact de ton ISO
    storage_name: "local-lvm"
    disk_size: "80G"
    memory: 4096
    cores: 2
    net_bridge: "vmbr0"

  tasks:
    - name: Création de la VM RHEL
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        node: "{{ node_name }}"
        vmid: "{{ vm_id }}"
        name: "{{ vm_name }}"
        iso: "{{ iso_name }}"
        storage: "{{ storage_name }}"
        disk: "{{ disk_size }}"
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        net:
          - model: virtio
            bridge: "{{ net_bridge }}"
        ostype: l26
        state: present
        scsihw: virtio-scsi-pci
        boot: cdn
        bootdisk: scsi0
        onboot: yes
        agent: 1
      delegate_to: localhost

    - name: Démarrage de la VM
      community.general.proxmox_kvm:
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        api_host: "{{ proxmox_host }}"
        node: "{{ node_name }}"
        vmid: "{{ vm_id }}"
        state: started
      delegate_to: localhost

