---
- name: Création de 6 VMs RHEL (3 en 9.6 et 3 en 10)
  hosts: localhost
  gather_facts: false
  collections:
    - community.general

  vars:
    api_user: "root@pam"
    api_password: "baraka"
    api_host: "192.168.1.56"
    vm_storage: "local-lvm"
    vm_bridge: "vmbr0"
    vm_memory: 4096
    vm_disk_size: 80
    rhel96_iso: "local:iso/rhel-9.6-x86_64-dvd.iso"
    rhel10_iso: "local:iso/rhel-10.0-x86_64-dvd.iso"

    vm_list:
      # --- RHEL 9.6 ---
      - { name: "rhel96-vm1", iso: "{{ rhel96_iso }}", id: 301 }
      - { name: "rhel96-vm2", iso: "{{ rhel96_iso }}", id: 302 }
      - { name: "rhel96-vm3", iso: "{{ rhel96_iso }}", id: 303 }

      # --- RHEL 10 ---
      - { name: "rhel10-vm1", iso: "{{ rhel10_iso }}", id: 311 }
      - { name: "rhel10-vm2", iso: "{{ rhel10_iso }}", id: 312 }
      - { name: "rhel10-vm3", iso: "{{ rhel10_iso }}", id: 313 }

  tasks:
    - name: Création des VMs RHEL
      community.general.proxmox_kvm:
        api_user: "{{ api_user }}"
        api_password: "{{ api_password }}"
        api_host: "{{ api_host }}"
        vmid: "{{ item.id }}"
        name: "{{ item.name }}"
        node: "pve"
        cores: 2
        memory: "{{ vm_memory }}"
        scsihw: virtio-scsi-pci
        ide2: "{{ item.iso }},media=cdrom"
        sata0: "{{ vm_storage }}:{{ vm_disk_size }}"
        net0: "virtio,bridge={{ vm_bridge }}"
        ostype: l26
        bootdisk: sata0
        boot: "cdn"
        state: present
        force: true
      loop: "{{ vm_list }}"

