---
- name: Création automatique d’une VM RHEL sur Proxmox
  hosts: localhost
  gather_facts: no

  vars:
    proxmox_host: "192.168.1.56"
    proxmox_user: "root@pam"
    proxmox_password: "baraka"   # Tu pourras ensuite le sécuriser dans un Credential AWX
    node: "pve"
    vmid: 120
    vm_name: "rhel-auto"
    iso_file: "rhel-9.5-x86_64-dvd.iso"
    storage: "local"
    disk_size: "30G"
    memory: "4096"
    cores: 2
    net_bridge: "vmbr0"

  tasks:

    - name: Création de la VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        name: "{{ vm_name }}"
        storage: "{{ storage }}"
        disk: "{{ disk_size }}"
        memory: "{{ memory }}"
        cores: "{{ cores }}"
        net0: "virtio,bridge={{ net_bridge }}"
        cdrom: "local:iso/{{ iso_file }}"
        ostype: "l26"
        onboot: yes
        boot: "cdn"
        state: present

    - name: Démarrer la VM
      community.general.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        state: started

